const customers:any = [
    {
      "id": 1,
      "Location Name": "Store A",
      "Master Category": "Topicals",
      "Order Date": "2023-01-01 00:00:00",
      "Customer Type": "Recreational",
      "Budtender Name": "Bob",
      "Gross Sales": 391.98,
      "Returned Amount": 0,
      "Discounted Amount": 9.13,
      "Loyalty as Discount": 0,
      "Net Sales": 382.85,
      "Inventory Cost": 217.69,
      "Inventory Profit": 165.16,
      "Loyalty as Payment": 9.41,
      "Tax Amount": 37.55,
      "Invoice Total": 410.99,
      "Amount Paid in Cash": 0,
      "Amount Paid in Debit": 410.99,
      "Birth Date": "1950-11-20 00:00:00",
      "Customer Name": "Michael Jones",
      "Product Name": "THC Patch",
    },
    {
      "id": 2,
      "Location Name": "Store A",
      "Master Category": "Topicals",
      "Order Date": "2023-01-01 00:00:00",
      "Customer Type": "Recreational",
      "Budtender Name": "Bob",
      "Gross Sales": 391.98,
      "Returned Amount": 0,
      "Discounted Amount": 9.13,
      "Loyalty as Discount": 0,
      "Net Sales": 382.85,
      "Inventory Cost": 217.69,
      "Inventory Profit": 165.16,
      "Loyalty as Payment": 9.41,
      "Tax Amount": 37.55,
      "Invoice Total": 410.99,
      "Amount Paid in Cash": 0,
      "Amount Paid in Debit": 410.99,
      "Birth Date": "1950-11-20 00:00:00",
      "Customer Name": "Michael Jones",
      "Product Name": "THC Patch",
    },
    {
      "id": 3,
      "Location Name": "Store A",
      "Master Category": "Topicals",
      "Order Date": "2023-01-01 00:00:00",
      "Customer Type": "Recreational",
      "Budtender Name": "Bob",
      "Gross Sales": 391.98,
      "Returned Amount": 0,
      "Discounted Amount": 9.13,
      "Loyalty as Discount": 0,
      "Net Sales": 382.85,
      "Inventory Cost": 217.69,
      "Inventory Profit": 165.16,
      "Loyalty as Payment": 9.41,
      "Tax Amount": 37.55,
      "Invoice Total": 410.99,
      "Amount Paid in Cash": 0,
      "Amount Paid in Debit": 410.99,
      "Birth Date": "1950-11-20 00:00:00",
      "Customer Name": "Michael Jones",
      "Product Name": "THC Patch",
    },
  ];
  
  export { customers };